version: "3.7"
services:

  spark-master:
    image: docker.io/bitnami/spark:3.1
    container_name: spark-master
    user: root # This parameter is key to let spark write on volumes
    hostname: spark-master
    ports:
      - "8080:8080"
    volumes:
      - ./apps/spark:/opt/spark-apps:rw
    environment:
      - "SPARK_LOCAL_IP=spark-master"



  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin-compose
    user: root # This parameter is key to let spark write on volumes
    ports:
      - "9090:8080"
    volumes:
      - /mnt/c/Users/asanturi/Documents/test/spark:/zeppelin/spark
    environment:
      - "ZEPPELIN_NOTEBOOK_DIR=/opt/zeppelin-notebooks"


